INSERT INTO "rating" VALUES
(1, 491, 181, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(2, 137, 101, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(3, 540, 79, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(4, 210, 156, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(5, 367, 77, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(6, 659, 50, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(7, 820, 57, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(8, 640, 54, 3, 'Hasilnya lumayan. Mungkin bisa lebih cepat dan komunikasi lebih jelas.'),
(9, 759, 45, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(10, 862, 152, 5, 'Pelayanannya sangat profesional dan hasilnya melampaui harapan. Bintang lima!'),
(11, 91, 54, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(12, 233, 61, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(13, 356, 156, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(14, 851, 152, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(15, 486, 86, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(16, 44, 74, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(17, 762, 96, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(18, 204, 125, 1, 'Sangat mengecewakan. Jangan buang uang Anda di sini. Saya ingin pengembalian dana!'),
(19, 894, 40, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(20, 403, 171, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(21, 991, 136, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(22, 511, 12, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(23, 774, 181, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(24, 418, 7, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(25, 889, 1, 4, 'Pelayanannya baik, komunikatif dan hasilnya sesuai. Puas!'),
(26, 291, 46, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(27, 803, 70, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(28, 562, 49, 2, 'Ada sedikit masalah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(29, 835, 154, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(30, 465, 164, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(31, 963, 170, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(32, 510, 185, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(33, 27, 181, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(34, 763, 71, 1, 'Ini berfungsi, tapi tidak lebih. Tidak ada nilai yang bisa dibanggakan.'),
(35, 611, 66, 1, 'Dia adalah kenikmatan besar yang kasar terhadap kesalahan. Saya tidak akan pernah kembali.'),
(36, 892, 127, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(37, 163, 92, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(38, 182, 49, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(39, 302, 158, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(40, 337, 36, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(41, 915, 27, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(42, 261, 107, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(43, 445, 25, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(44, 110, 64, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(45, 876, 23, 3, 'Sedang-sedang saja. Saya berharap ada sedikit lebih banyak fitur.'),
(46, 336, 37, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(47, 35, 104, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(48, 894, 63, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(49, 728, 119, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(50, 704, 100, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(51, 811, 182, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(52, 450, 118, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(53, 805, 76, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(54, 697, 37, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(55, 441, 72, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(56, 13, 196, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(57, 506, 4, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(58, 746, 87, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(59, 321, 117, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(60, 115, 144, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(61, 208, 116, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(62, 970, 125, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(63, 550, 27, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(64, 841, 94, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(65, 620, 61, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(66, 746, 116, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(67, 68, 184, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(68, 1, 52, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(69, 718, 66, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(70, 722, 137, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(71, 470, 150, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(72, 839, 84, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(73, 216, 10, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(74, 333, 140, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(75, 74, 145, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(76, 1, 198, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(77, 606, 156, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(78, 789, 59, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(79, 266, 161, 5, 'Terima kasih banyak! Ini adalah solusi yang saya cari. Fantastis!'),
(80, 133, 7, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(81, 210, 129, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(82, 998, 109, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(83, 695, 4, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(84, 862, 145, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(85, 464, 98, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(86, 226, 105, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(87, 189, 157, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(88, 26, 101, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(89, 840, 45, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(90, 891, 7, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(91, 323, 66, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(92, 891, 137, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(93, 482, 159, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(94, 594, 55, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(95, 21, 132, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(96, 294, 153, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(97, 437, 89, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(98, 628, 144, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(99, 620, 62, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(100, 664, 156, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(101, 869, 111, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(102, 476, 105, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(103, 669, 98, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(104, 97, 135, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(105, 301, 156, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(106, 51, 94, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(107, 603, 147, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(108, 670, 165, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(109, 246, 115, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(110, 106, 110, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(111, 602, 40, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(112, 948, 24, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(113, 611, 153, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(114, 852, 32, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(115, 643, 76, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(116, 886, 41, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(117, 964, 16, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(118, 793, 30, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(119, 504, 142, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(120, 307, 2, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(121, 346, 31, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(122, 417, 92, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(123, 539, 9, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(124, 796, 61, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(125, 625, 97, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(126, 812, 197, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(127, 825, 104, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(128, 551, 180, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(129, 34, 132, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(130, 488, 70, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(131, 720, 43, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(132, 725, 129, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(133, 44, 89, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(134, 559, 59, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(135, 889, 137, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(136, 428, 62, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(137, 653, 27, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(138, 335, 62, 3, 'Hasilnya lumayan. Mungkin bisa lebih cepat dan komunikasi lebih jelas.'),
(139, 555, 115, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(140, 581, 74, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(141, 195, 153, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(142, 585, 184, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(143, 304, 74, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(144, 872, 67, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(145, 783, 110, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(146, 982, 6, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(147, 81, 15, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(148, 904, 40, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(149, 541, 31, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(150, 735, 135, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(151, 470, 82, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(152, 275, 159, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(153, 204, 54, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(154, 783, 87, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(155, 311, 125, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(156, 512, 62, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(157, 344, 85, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(158, 115, 53, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(159, 803, 199, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(160, 942, 133, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(161, 941, 154, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(162, 38, 99, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(163, 26, 12, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(164, 36, 120, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(165, 9, 10, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(166, 407, 165, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(167, 261, 47, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(168, 552, 64, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(169, 463, 162, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(170, 287, 186, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(171, 873, 32, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(172, 325, 157, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(173, 545, 94, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(174, 112, 59, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(175, 967, 113, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(176, 181, 87, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(177, 817, 160, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(178, 897, 122, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(179, 396, 78, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(180, 710, 175, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(181, 966, 162, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(182, 437, 197, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(183, 748, 138, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(184, 58, 116, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(185, 176, 18, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(186, 882, 66, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(187, 99, 55, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(188, 97, 121, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(189, 361, 21, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(190, 820, 129, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(191, 218, 155, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(192, 18, 190, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(193, 500, 14, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(194, 103, 25, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(195, 45, 116, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(196, 518, 14, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(197, 743, 131, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(198, 840, 136, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(199, 563, 111, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(200, 637, 19, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(201, 389, 81, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(202, 755, 50, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(203, 921, 124, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(204, 712, 140, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(205, 419, 189, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(206, 564, 146, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(207, 584, 192, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(208, 407, 78, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(209, 334, 11, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(210, 11, 131, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(211, 491, 42, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(212, 516, 9, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(213, 207, 159, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(214, 460, 54, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(215, 256, 187, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(216, 635, 188, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(217, 1000, 87, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(218, 812, 120, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(219, 659, 112, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(220, 429, 38, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(221, 964, 172, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(222, 977, 196, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(223, 664, 138, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(224, 609, 105, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(225, 560, 104, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(226, 272, 160, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(227, 10, 63, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(228, 961, 44, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(229, 942, 164, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(230, 139, 146, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(231, 735, 110, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(232, 882, 31, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(233, 517, 165, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(234, 71, 157, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(235, 654, 87, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(236, 359, 113, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(237, 120, 123, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(238, 212, 73, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(239, 403, 134, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(240, 484, 101, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(241, 350, 145, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(242, 326, 39, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(243, 141, 1, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(244, 547, 189, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(245, 673, 101, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(246, 223, 92, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(247, 426, 126, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(248, 684, 40, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(249, 50, 69, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(250, 4, 195, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(251, 188, 109, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(252, 675, 188, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(253, 864, 157, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(254, 885, 159, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(255, 273, 41, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(256, 904, 12, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(257, 475, 172, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(258, 190, 159, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(259, 448, 108, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(260, 243, 167, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(261, 296, 28, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(262, 388, 172, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(263, 29, 86, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(264, 195, 153, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(265, 195, 23, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(266, 343, 159, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(267, 43, 195, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(268, 806, 197, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(269, 812, 139, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(270, 836, 51, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(271, 635, 35, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(272, 980, 141, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(273, 741, 39, 1, 'Benar-benar kacau! Produknya datang rusak dan tidak ada yang mau bertanggung jawab.'),
(274, 521, 26, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(275, 986, 29, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(276, 326, 182, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(277, 793, 118, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(278, 923, 123, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(279, 14, 104, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(280, 256, 91, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(281, 66, 5, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(282, 404, 98, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(283, 638, 118, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(284, 564, 162, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(285, 458, 68, 1, 'Sangat buruk! Benar-benar buang-buang uang.'),
(286, 489, 160, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(287, 85, 89, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(288, 803, 110, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(289, 44, 6, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(290, 368, 107, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(291, 827, 125, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(292, 493, 169, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(293, 313, 7, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(294, 345, 109, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(295, 686, 178, 1, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(296, 39, 13, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(297, 356, 179, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(298, 135, 25, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(299, 121, 83, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(300, 457, 38, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(301, 766, 164, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(302, 10, 164, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(303, 284, 160, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(304, 619, 81, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(305, 177, 192, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(306, 753, 79, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(307, 746, 2, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(308, 598, 55, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(309, 587, 36, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(310, 947, 156, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(311, 874, 162, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(312, 114, 175, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(313, 100, 159, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(314, 532, 130, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(315, 606, 171, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(316, 135, 146, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(317, 387, 185, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(318, 937, 110, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(319, 692, 13, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(320, 50, 166, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(321, 620, 170, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(322, 600, 102, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(323, 722, 57, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(324, 762, 132, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(325, 303, 101, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(326, 689, 144, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(327, 437, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(328, 482, 112, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(329, 946, 110, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(330, 893, 110, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(331, 885, 162, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(332, 696, 52, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(333, 908, 127, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(334, 15, 96, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(335, 755, 100, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(336, 13, 162, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(337, 695, 102, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(338, 977, 50, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(339, 442, 65, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(340, 89, 49, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(341, 107, 104, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(342, 461, 174, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(343, 638, 59, 1, 'Sangat mengecewakan! Layanan buruk dan tempatnya tidak terawat. Jangan pernah mencoba.'),
(344, 46, 53, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(345, 96, 115, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(346, 137, 85, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(347, 863, 101, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(348, 634, 188, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(349, 936, 134, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(350, 488, 110, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(351, 936, 135, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(352, 634, 142, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(353, 915, 119, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(354, 335, 116, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(355, 946, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(356, 477, 153, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(357, 988, 163, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(358, 608, 155, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(359, 396, 103, 1, 'Benar-benar **buruk**. Saya hanya memberikan satu bintang karena tidak ada pilihan nol bintang.'),
(360, 419, 112, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(361, 803, 181, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(362, 856, 168, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(363, 532, 105, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(364, 461, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(365, 876, 142, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(366, 827, 101, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(367, 851, 109, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(368, 664, 116, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(369, 746, 119, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(370, 774, 127, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(371, 712, 177, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(372, 755, 101, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(373, 540, 185, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(374, 603, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(375, 44, 148, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(376, 756, 188, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(377, 518, 176, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(378, 62, 148, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(379, 368, 172, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(380, 237, 50, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(381, 712, 112, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(382, 381, 115, 2, 'Ada yang salah, dan konsekuensinya terasa. Saya sangat kecewa.'),
(383, 335, 181, 1, 'Tidak dapat digunakan. Ada banyak bug/masalah sejak awal. Benar-benar sampah!'),
(384, 574, 102, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(385, 437, 106, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(386, 15, 181, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(387, 85, 163, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(388, 836, 128, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(389, 786, 168, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(390, 756, 184, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(391, 563, 169, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(392, 163, 107, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(393, 226, 173, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(394, 762, 108, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(395, 606, 110, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(396, 584, 188, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(397, 892, 115, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(398, 963, 125, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(399, 581, 133, 1, 'Saya sangat kecewa. Mereka berjanji terlalu banyak dan gagal memenuhi janji.'),
(400, 400, 106, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(401, 746, 171, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(402, 1000, 171, 1, 'Ini adalah pengalaman terburuk. Produknya rusak saat tiba dan layanan pelanggan lambat.'),
(403, 304, 112, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(404, 574, 177, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(405, 50, 172, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(406, 441, 118, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(407, 482, 176, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(408, 921, 115, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(409, 874, 161, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(410, 804, 177, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(411, 44, 183, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(412, 190, 169, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(413, 38, 144, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(414, 500, 112, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(415, 12, 118, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(416, 967, 104, 1, 'Mengerikan. Produk tidak sesuai gambar, kualitas sangat rendah. Penipuan!'),
(417, 720, 175, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(418, 484, 110, 2, 'Mengecewakan. Saya merasa produk/layanan tidak sesuai dengan deskripsi. Perlu perbaikan.'),
(419, 893, 101, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(420, 500, 185, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(421, 89, 145, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(422, 608, 183, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(423, 762, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(424, 735, 142, 2, 'Pengalaman kurang menyenangkan. Banyak masalah teknis yang tidak diselesaikan.'),
(425, 461, 175, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(426, 321, 162, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(427, 477, 105, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(428, 774, 185, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(429, 696, 175, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(430, 482, 142, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(431, 804, 118, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(432, 908, 174, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa dilakukan.'),
(433, 91, 109, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(434, 584, 169, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(435, 15, 101, 2, 'Saya tidak akan merekomendasikan ini. Ada banyak pilihan yang lebih baik di luar sana.'),
(436, 188, 106, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(437, 608, 174, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(438, 936, 161, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(439, 442, 117, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(440, 559, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(441, 139, 113, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(442, 407, 108, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(443, 863, 107, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(444, 112, 185, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(445, 497, 175, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(446, 560, 107, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(447, 423, 183, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(448, 62, 155, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(449, 137, 155, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(450, 461, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(451, 606, 174, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(452, 23, 110, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(453, 563, 154, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(454, 695, 118, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(455, 963, 160, 2, 'Saya berharap lebih. Produk/layanan di bawah standar.'),
(456, 474, 169, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(457, 426, 174, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(458, 551, 176, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(459, 876, 119, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(460, 100, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(461, 389, 112, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(462, 609, 113, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(463, 856, 119, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(464, 400, 173, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(465, 874, 185, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(466, 689, 178, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(467, 368, 174, 2, 'Kualitasnya jauh di bawah standar. Saya merasa ditipu.'),
(468, 796, 177, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(469, 539, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(470, 423, 119, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(471, 915, 175, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(472, 237, 178, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(473, 517, 183, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(474, 461, 107, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(475, 597, 172, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(476, 458, 174, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(477, 442, 107, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(478, 50, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(479, 746, 175, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(480, 895, 118, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(481, 13, 101, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(482, 103, 113, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(483, 85, 118, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(484, 574, 113, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(485, 62, 183, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(486, 96, 107, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(487, 863, 112, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(488, 403, 118, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(489, 44, 112, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(490, 831, 171, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(491, 560, 119, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(492, 598, 178, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(493, 114, 183, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(494, 609, 106, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(495, 597, 118, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(496, 908, 176, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(497, 755, 119, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(498, 407, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(499, 564, 183, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(500, 11, 178, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(501, 746, 181, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(502, 608, 119, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(503, 350, 176, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(504, 876, 174, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(505, 753, 183, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(506, 915, 110, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(507, 762, 118, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(508, 893, 176, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(509, 650, 119, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(510, 303, 174, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(511, 493, 112, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(512, 13, 175, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(513, 14, 119, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(514, 302, 176, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(515, 62, 174, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(516, 804, 109, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(517, 856, 175, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(518, 936, 112, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(519, 112, 175, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(520, 689, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(521, 563, 110, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(522, 474, 185, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(523, 139, 175, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(524, 831, 118, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(525, 44, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(526, 755, 175, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(527, 461, 104, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(528, 908, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(529, 696, 113, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(530, 407, 119, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(531, 103, 174, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(532, 597, 107, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(533, 560, 174, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(534, 423, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(535, 874, 175, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(536, 442, 112, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(537, 774, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(538, 559, 178, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(539, 497, 113, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(540, 684, 175, 3, 'Lumayan, hanya fungsionalitas dasar yang terpenuhi. Kurang inovasi.'),
(541, 12, 175, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(542, 482, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(543, 609, 172, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(544, 96, 119, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(545, 804, 174, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(546, 598, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(547, 493, 175, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(548, 650, 118, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(549, 100, 113, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(550, 477, 175, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(551, 831, 104, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(552, 91, 119, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(553, 389, 175, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(554, 114, 176, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(555, 608, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(556, 13, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(557, 14, 118, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(558, 302, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(559, 62, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(560, 804, 175, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(561, 856, 176, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(562, 936, 175, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(563, 112, 110, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(564, 689, 174, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(565, 139, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(566, 44, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(567, 755, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(568, 461, 172, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(569, 597, 175, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(570, 560, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(571, 423, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(572, 874, 113, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(573, 442, 178, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(574, 559, 175, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(575, 497, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(576, 684, 110, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(577, 12, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(578, 482, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(579, 609, 175, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(580, 96, 176, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(581, 598, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(582, 493, 110, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(583, 650, 176, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(584, 100, 175, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(585, 477, 110, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(586, 831, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(587, 91, 176, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(588, 389, 110, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(589, 114, 175, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(590, 608, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(591, 13, 119, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(592, 14, 176, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(593, 302, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(594, 62, 175, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(595, 804, 110, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(596, 856, 172, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(597, 936, 113, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(598, 112, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(599, 689, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(600, 139, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(601, 44, 176, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(602, 755, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(603, 461, 110, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(604, 597, 172, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(605, 560, 176, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(606, 423, 110, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(607, 874, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(608, 442, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(609, 559, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(610, 497, 110, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(611, 684, 176, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(612, 12, 176, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(613, 482, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(614, 609, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(615, 96, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(616, 598, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(617, 493, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(618, 650, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(619, 100, 176, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(620, 477, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(621, 831, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(622, 91, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(623, 389, 176, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(624, 114, 113, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(625, 608, 176, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(626, 13, 176, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(627, 14, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(628, 302, 175, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(629, 62, 176, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(630, 804, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(631, 856, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(632, 936, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(633, 112, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(634, 689, 176, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(635, 139, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(636, 44, 110, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(637, 755, 176, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(638, 461, 176, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(639, 597, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(640, 560, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(641, 423, 176, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(642, 874, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(643, 442, 176, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(644, 559, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(645, 497, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(646, 684, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(647, 12, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(648, 482, 176, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(649, 609, 110, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(650, 96, 110, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(651, 598, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(652, 493, 176, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(653, 650, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(654, 100, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(655, 477, 176, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(656, 831, 176, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(657, 91, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(658, 389, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(659, 114, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(660, 608, 113, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(661, 13, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(662, 14, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(663, 302, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(664, 62, 113, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(665, 804, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(666, 856, 176, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(667, 936, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(668, 112, 172, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(669, 689, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(670, 139, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(671, 44, 172, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(672, 755, 110, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(673, 461, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(674, 597, 176, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(675, 560, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(676, 423, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(677, 874, 176, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(678, 442, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(679, 559, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(680, 497, 176, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(681, 684, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(682, 12, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(683, 482, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(684, 609, 176, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(685, 96, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(686, 598, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(687, 493, 113, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(688, 650, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(689, 100, 110, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(690, 477, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(691, 831, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(692, 91, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(693, 389, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(694, 114, 172, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(695, 608, 110, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(696, 13, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(697, 14, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(698, 302, 176, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(699, 62, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(700, 804, 176, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(701, 856, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(702, 936, 176, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(703, 112, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(704, 689, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(705, 139, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(706, 44, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(707, 755, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(708, 461, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(709, 597, 110, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(710, 560, 176, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(711, 423, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(712, 874, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(713, 442, 172, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(714, 559, 176, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(715, 497, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(716, 684, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(717, 12, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(718, 482, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(719, 609, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(720, 96, 113, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(721, 598, 175, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(722, 493, 176, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(723, 650, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(724, 100, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(725, 477, 110, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(726, 831, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(727, 91, 175, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(728, 389, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(729, 114, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(730, 608, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(731, 13, 175, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(732, 14, 110, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(733, 302, 110, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(734, 62, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(735, 804, 110, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(736, 856, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(737, 936, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(738, 112, 176, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(739, 689, 110, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(740, 139, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(741, 44, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(742, 755, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(743, 461, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(744, 597, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(745, 560, 110, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(746, 423, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(747, 874, 113, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(748, 442, 110, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(749, 559, 176, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(750, 497, 172, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(751, 684, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(752, 12, 176, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(753, 482, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(754, 609, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(755, 96, 176, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(756, 598, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(757, 493, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(758, 650, 176, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(759, 100, 175, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(760, 477, 175, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(761, 831, 175, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(762, 91, 110, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(763, 389, 175, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(764, 114, 176, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(765, 608, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(766, 13, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(767, 14, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(768, 302, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(769, 62, 176, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(770, 804, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(771, 856, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(772, 936, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(773, 112, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(774, 689, 176, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(775, 139, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(776, 44, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(777, 755, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(778, 461, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(779, 597, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(780, 560, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(781, 423, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(782, 874, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(783, 442, 176, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(784, 559, 113, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(785, 497, 110, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(786, 684, 176, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(787, 12, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(788, 482, 176, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(789, 609, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(790, 96, 175, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(791, 598, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(792, 493, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(793, 650, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(794, 100, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(795, 477, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(796, 831, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(797, 91, 176, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(798, 389, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(799, 114, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(800, 608, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(801, 13, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(802, 14, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(803, 302, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(804, 62, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(805, 804, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(806, 856, 175, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(807, 936, 110, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(808, 112, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(809, 689, 113, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(810, 139, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(811, 44, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(812, 755, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(813, 461, 176, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(814, 597, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(815, 560, 176, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(816, 423, 110, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(817, 874, 176, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(818, 442, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(819, 559, 172, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(820, 497, 175, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(821, 684, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(822, 12, 175, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(823, 482, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(824, 609, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(825, 96, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(826, 598, 176, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(827, 493, 110, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(828, 650, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(829, 100, 176, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(830, 477, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(831, 831, 110, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(832, 91, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(833, 389, 176, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(834, 114, 172, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(835, 608, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(836, 13, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(837, 14, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(838, 302, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(839, 62, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(840, 804, 176, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(841, 856, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(842, 936, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(843, 112, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(844, 689, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(845, 139, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(846, 44, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(847, 755, 110, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(848, 461, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(849, 597, 176, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(850, 560, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(851, 423, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(852, 874, 176, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(853, 442, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(854, 559, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(855, 497, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(856, 684, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(857, 12, 172, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(858, 482, 110, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(859, 609, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(860, 96, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(861, 598, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(862, 493, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(863, 650, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(864, 100, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(865, 477, 176, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(866, 831, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(867, 91, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(868, 389, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(869, 114, 113, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(870, 608, 172, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(871, 13, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(872, 14, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(873, 302, 175, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(874, 62, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(875, 804, 175, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(876, 856, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(877, 936, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(878, 112, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(879, 689, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(880, 139, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(881, 44, 176, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(882, 755, 176, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(883, 461, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(884, 597, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(885, 560, 176, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(886, 423, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(887, 874, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(888, 442, 113, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(889, 559, 176, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(890, 497, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(891, 684, 110, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(892, 12, 113, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(893, 482, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(894, 609, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(895, 96, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(896, 598, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(897, 493, 176, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(898, 650, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(899, 100, 175, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(900, 477, 110, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(901, 831, 175, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(902, 91, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(903, 389, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(904, 114, 176, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(905, 608, 176, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(906, 13, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(907, 14, 113, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(908, 302, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(909, 62, 176, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(910, 804, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(911, 856, 176, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(912, 936, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(913, 112, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(914, 689, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(915, 139, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(916, 44, 172, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(917, 755, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(918, 461, 175, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(919, 597, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(920, 560, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(921, 423, 175, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(922, 874, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(923, 442, 176, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(924, 559, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(925, 497, 176, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(926, 684, 176, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(927, 12, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(928, 482, 176, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(929, 609, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(930, 96, 172, 3, 'Biasa saja. Saya tidak akan membelinya lagi, tapi juga tidak mengajukan keluhan.'),
(931, 598, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(932, 493, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(933, 650, 175, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(934, 100, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(935, 477, 113, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(936, 831, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(937, 91, 110, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(938, 389, 176, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(939, 114, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(940, 608, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(941, 13, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(942, 14, 176, 4, 'Pelayanannya baik, cepat dan ramah. Saya akan kembali lagi.'),
(943, 302, 110, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(944, 62, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(945, 804, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(946, 856, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(947, 936, 176, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(948, 112, 175, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(949, 689, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(950, 139, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(951, 44, 176, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(952, 755, 175, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(953, 461, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(954, 597, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(955, 560, 172, 3, 'Cukup memadai. Fasilitasnya standar, bisa dibilang biasa-biasa saja.'),
(956, 423, 113, 5, 'Komitmen pada kualitas yang luar biasa. Saya sangat senang dengan hasilnya.'),
(957, 874, 172, 3, 'Saya tidak punya pendapat yang kuat, netral saja. Bisa lebih baik.'),
(958, 442, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(959, 559, 113, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(960, 497, 110, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(961, 684, 175, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(962, 12, 176, 5, 'Pilihan yang cepat dan sangat mudah! Tidak ada keluhan sama sekali. Pekerjaan yang luar biasa.'),
(963, 482, 113, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(964, 609, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(965, 96, 175, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(966, 598, 176, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(967, 493, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(968, 650, 110, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(969, 100, 172, 3, 'Agak membingungkan di beberapa bagian. Perlu petunjuk yang lebih jelas.'),
(970, 477, 176, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.'),
(971, 831, 110, 4, 'Desain yang bagus dan rapi, pengerjaan cepat. Ada sedikit detail kecil yang bisa ditingkatkan.'),
(972, 91, 175, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(973, 389, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(974, 114, 113, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(975, 608, 172, 3, 'Hanya fungsionalitas standar. Tidak ada yang istimewa, tapi berfungsi.'),
(976, 13, 110, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(977, 14, 175, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(978, 302, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(979, 62, 113, 5, 'Pilihan sempurna untuk kebutuhan saya. Hasilnya sangat memuaskan.'),
(980, 804, 172, 3, 'Rata-rata saja. Tidak ada yang buruk, tapi tidak ada yang istimewa. Sesuai dengan harganya.'),
(981, 856, 110, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(982, 936, 175, 4, 'Pengerjaan bagus, detail rapi. Hanya waktu tunggu yang sedikit lama.'),
(983, 112, 110, 4, 'Layanan yang sangat memuaskan, tetapi saya merasa harganya terlalu tinggi.'),
(984, 689, 176, 5, 'Luar biasa! Arsiteknya bekerja keras dan hasilnya memuaskan. Sangat direkomendasikan!'),
(985, 139, 113, 5, 'Kualitas terbaik. Investasi yang sangat berharga dan hasil yang fantastis.'),
(986, 44, 176, 5, 'Sangat sempurna, desain yang indah dan fasilitas yang lengkap. Ini pengalaman terbaik!'),
(987, 755, 110, 4, 'Tim yang hebat, sangat membantu dan responsif. Akan merekomendasikan.'),
(988, 461, 176, 4, 'Perbaikan yang cepat dan efektif. Sekarang semuanya berfungsi dengan baik.'),
(989, 597, 172, 3, 'Kurang lebih lumayan. Tidak ada masalah, tetapi tidak ada nilai tambah.'),
(990, 560, 110, 4, 'Pekerjaan yang memuaskan dan memenuhi ekspektasi. Sangat direkomendasikan.'),
(991, 423, 176, 5, 'Mutu luar biasa! Ini sepadan dengan uang yang dikeluarkan. Sangat bagus.'),
(992, 874, 175, 4, 'Hasil pengerjaan sesuai spesifikasi. Dapat diandalkan dan profesional.'),
(993, 442, 113, 5, 'Layanan super cepat dan hasilnya melebihi ekspektasi. Terima kasih banyak!'),
(994, 559, 172, 3, 'Produknya standar. Tidak ada yang salah, tapi tidak ada yang menonjol. Seperti yang diharapkan.'),
(995, 497, 110, 4, 'Cepat dan responsif. Mereka mengerti kebutuhan saya dengan baik.'),
(996, 684, 172, 3, 'Prosesnya standar dan memakan waktu sedikit. Tidak buruk, tapi tidak efisien.'),
(997, 12, 113, 5, 'Pelayanan yang fantastis. Mereka melampaui tugasnya untuk membantu saya.'),
(998, 482, 175, 4, 'Secara keseluruhan bagus, namun ada sedikit perbaikan kecil yang bisa ditingkatkan.'),
(999, 609, 176, 4, 'Semua berjalan lancar. Hasilnya akurat dan memenuhi harapan. Tim yang ramah.'),
(1000, 96, 113, 5, 'Mereka mengurus semuanya dengan sempurna. Saya tidak perlu khawatir sama sekali.');
